### ISSUE TITLE
Who watches the watcher?

### ISSUE THREAD

**Issue by SleeperSmith** [imomou/LogFarm#1]
Where does LogFarm's log go? Where do the exception in LogFarm get logged to?

**Comment by imomou** [comment]
Hi SleeperSmith, thank you for your question and interest in LogFarm. Right now, it has support for Nlog and Elmah.

1.  NLog will ship logs to CloudWatchLog which it has a really good native support for log collection and digestion and of course it also provide some basic visualization of the logs. However I'm hoping  I can provide a cloudformation template to provide log visualisation in a more centralized approach, something like ElasticSearch with Kibana.
2., Elmah, right now it has the ability the capture any exception occured under http mvc, and it ships to DynamoDb.

I will add more different kind logs in the future, I think right now metrics collection is missing for LogFarm, so I will look into miniprofiler or stackify.

Cheers
Sam
