### ISSUE TITLE
Allow overidable logstream suffix/identifier

### ISSUE THREAD

**Issue by SleeperSmith** [imomou/LogFarm#2]
![image](https://cloud.githubusercontent.com/assets/1109339/23099437/e836c2ac-f6ba-11e6-89ad-86d71be42388.png)

When the logstream name is being determined

The instance metadata is used. I think (don't quote me on this) this potentially blocks the application from starting. Eitherway, I think it's a good idea to provide a field to override that suffix string and prevent the instance metadata from being even called in the first place. If you are on a non aws ec2 host, all your logs will be delayed by 60 seconds.

**Comment by imomou** [comment]
Thanks SleepSmith, address this issue as you recommended. cheers
