### ISSUE TITLE
Use ${logger} instead of ${callsite}

### ISSUE THREAD

**Issue by SleeperSmith** [imomou/LogFarm#3]
https://github.com/imomou/LogFarm/blob/master/src/nuget/aws/NLog.config

Really should be using logger name instead of callsite.

**Comment by imomou** [comment]
Hi SleeperSmiths, thanks for raising an issue once again, it make sense to use logger instead callsite, else user wont have the ability to change the name of the logger when instantiating - ILog GetLogger(string name) and is probably easier to deal with parsing logs later on. However I think there's advantage using callsite, it will provide information which method has logged an event e.g. MyApplication.Application_Start vs MyApplication.MvcApplication

**Comment by imomou** [comment]
I will add both callsite and logger to layout, thanks
